version: '3.8'

name: 'authentication'

services:
  authentication:
    container_name: auth
    image: authentication
    hostname: auth
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      microservices-cashflow:
        ipv4_address: ${IP_ADDRESS}

networks:
  microservices-cashflow:
    external: true