version: '3.8'

name: 'cash-in'

services:
  cash-in:
    container_name: cash-in
    image: cash-in
    hostname: cash-in
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3001:3001'
    networks:
      microservices-cashflow:
        ipv4_address: ${IP_ADDRESS}

networks:
  microservices-cashflow:
    external: true