version: '3.8'

name: 'wallet'

services:
  wallet:
    container_name: wallet
    image: wallet
    hostname: wallet
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3003:3003'
    networks:
      microservices-cashflow:
        ipv4_address: ${IP_ADDRESS}

networks:
  microservices-cashflow:
    external: true