version: '3.8'

name: 'balance'

services:
  balance:
    container_name: balance
    image: balance
    hostname: balance
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3004:3004'
    networks:
      microservices-cashflow:
        ipv4_address: ${IP_ADDRESS}

networks:
  microservices-cashflow:
    external: true