version: '3.8'

name: 'cash-out'

services:
  cash-out:
    container_name: cash-out
    image: cash-out
    hostname: cash-out
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3002:3002'
    networks:
      microservices-cashflow:
        ipv4_address: ${IP_ADDRESS}

networks:
  microservices-cashflow:
    external: true