version: '3.8'

name: 'auth-db'

services:
  auth-db:
    image: postgres:15
    container_name: auth-db
    hostname: auth-db
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      microservices-cashflow:
        ipv4_address: ${IP_ADDRESS}
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  microservices-cashflow:
    external: true